/**
 * Yanshee RESTful API
 *  ## 概述 Yanshee RESTful APIs是由使用[swagger-codegen](https://github.com/swagger-api/swagger-codegen)基于 [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki)的工程。 所有的API由Flask的[Connexion](https://github.com/zalando/connexion)来解释。 Yanshee-ROS中的apollo提供所有的RESTful APIs服务。 同时Yanshee RESTful APIs提供英文和中文两个版本： - [英文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [中文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## 依赖 Python 2.7 or 3.4+  
 *
 * OpenAPI spec version: 1.0.1
 * Contact: swenggroup@ubtrobot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGDevicesLED.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGDevicesLED::SWGDevicesLED(QString json) {
    init();
    this->fromJson(json);
}

SWGDevicesLED::SWGDevicesLED() {
    init();
}

SWGDevicesLED::~SWGDevicesLED() {
    this->cleanup();
}

void
SWGDevicesLED::init() {
    type = new QString("");
    m_type_isSet = false;
    color = new QString("");
    m_color_isSet = false;
    mode = new QString("");
    m_mode_isSet = false;
}

void
SWGDevicesLED::cleanup() {
    if(type != nullptr) { 
        delete type;
    }
    if(color != nullptr) { 
        delete color;
    }
    if(mode != nullptr) { 
        delete mode;
    }
}

SWGDevicesLED*
SWGDevicesLED::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGDevicesLED::fromJsonObject(QJsonObject pJson) {
    ::Swagger::setValue(&type, pJson["type"], "QString", "QString");
    
    ::Swagger::setValue(&color, pJson["color"], "QString", "QString");
    
    ::Swagger::setValue(&mode, pJson["mode"], "QString", "QString");
    
}

QString
SWGDevicesLED::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
SWGDevicesLED::asJsonObject() {
    QJsonObject obj;
    if(type != nullptr && *type != QString("")){
        toJsonValue(QString("type"), type, obj, QString("QString"));
    }
    if(color != nullptr && *color != QString("")){
        toJsonValue(QString("color"), color, obj, QString("QString"));
    }
    if(mode != nullptr && *mode != QString("")){
        toJsonValue(QString("mode"), mode, obj, QString("QString"));
    }

    return obj;
}

QString*
SWGDevicesLED::getType() {
    return type;
}
void
SWGDevicesLED::setType(QString* type) {
    this->type = type;
    this->m_type_isSet = true;
}

QString*
SWGDevicesLED::getColor() {
    return color;
}
void
SWGDevicesLED::setColor(QString* color) {
    this->color = color;
    this->m_color_isSet = true;
}

QString*
SWGDevicesLED::getMode() {
    return mode;
}
void
SWGDevicesLED::setMode(QString* mode) {
    this->mode = mode;
    this->m_mode_isSet = true;
}


bool
SWGDevicesLED::isSet(){
    bool isObjectUpdated = false;
    do{
        if(type != nullptr && *type != QString("")){ isObjectUpdated = true; break;}
        if(color != nullptr && *color != QString("")){ isObjectUpdated = true; break;}
        if(mode != nullptr && *mode != QString("")){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

