/**
 * Yanshee RESTful API
 *  ## 概述 Yanshee RESTful APIs是由使用[swagger-codegen](https://github.com/swagger-api/swagger-codegen)基于 [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki)的工程。 所有的API由Flask的[Connexion](https://github.com/zalando/connexion)来解释。 Yanshee-ROS中的apollo提供所有的RESTful APIs服务。 同时Yanshee RESTful APIs提供英文和中文两个版本： - [英文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [中文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## 依赖 Python 2.7 or 3.4+  
 *
 * OpenAPI spec version: 1.0.1
 * Contact: swenggroup@ubtrobot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGMotionsOperation.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGMotionsOperation::SWGMotionsOperation(QString json) {
    init();
    this->fromJson(json);
}

SWGMotionsOperation::SWGMotionsOperation() {
    init();
}

SWGMotionsOperation::~SWGMotionsOperation() {
    this->cleanup();
}

void
SWGMotionsOperation::init() {
    operation = new QString("");
    m_operation_isSet = false;
    motion = new SWGMotionsParameter();
    m_motion_isSet = false;
    timestamp = 0L;
    m_timestamp_isSet = false;
}

void
SWGMotionsOperation::cleanup() {
    if(operation != nullptr) { 
        delete operation;
    }
    if(motion != nullptr) { 
        delete motion;
    }

}

SWGMotionsOperation*
SWGMotionsOperation::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGMotionsOperation::fromJsonObject(QJsonObject pJson) {
    ::Swagger::setValue(&operation, pJson["operation"], "QString", "QString");
    
    ::Swagger::setValue(&motion, pJson["motion"], "SWGMotionsParameter", "SWGMotionsParameter");
    
    ::Swagger::setValue(&timestamp, pJson["timestamp"], "qint64", "");
    
}

QString
SWGMotionsOperation::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
SWGMotionsOperation::asJsonObject() {
    QJsonObject obj;
    if(operation != nullptr && *operation != QString("")){
        toJsonValue(QString("operation"), operation, obj, QString("QString"));
    }
    if((motion != nullptr) && (motion->isSet())){
        toJsonValue(QString("motion"), motion, obj, QString("SWGMotionsParameter"));
    }
    if(m_timestamp_isSet){
        obj.insert("timestamp", QJsonValue(timestamp));
    }

    return obj;
}

QString*
SWGMotionsOperation::getOperation() {
    return operation;
}
void
SWGMotionsOperation::setOperation(QString* operation) {
    this->operation = operation;
    this->m_operation_isSet = true;
}

SWGMotionsParameter*
SWGMotionsOperation::getMotion() {
    return motion;
}
void
SWGMotionsOperation::setMotion(SWGMotionsParameter* motion) {
    this->motion = motion;
    this->m_motion_isSet = true;
}

qint64
SWGMotionsOperation::getTimestamp() {
    return timestamp;
}
void
SWGMotionsOperation::setTimestamp(qint64 timestamp) {
    this->timestamp = timestamp;
    this->m_timestamp_isSet = true;
}


bool
SWGMotionsOperation::isSet(){
    bool isObjectUpdated = false;
    do{
        if(operation != nullptr && *operation != QString("")){ isObjectUpdated = true; break;}
        if(motion != nullptr && motion->isSet()){ isObjectUpdated = true; break;}
        if(m_timestamp_isSet){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

