/**
 * Yanshee RESTful API
 *  ## 概述 Yanshee RESTful APIs是由使用[swagger-codegen](https://github.com/swagger-api/swagger-codegen)基于 [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki)的工程。 所有的API由Flask的[Connexion](https://github.com/zalando/connexion)来解释。 Yanshee-ROS中的apollo提供所有的RESTful APIs服务。 同时Yanshee RESTful APIs提供英文和中文两个版本： - [英文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [中文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## 依赖 Python 2.7 or 3.4+  
 *
 * OpenAPI spec version: 1.0.1
 * Contact: swenggroup@ubtrobot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGSensorsInfraredValue.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGSensorsInfraredValue::SWGSensorsInfraredValue(QString json) {
    init();
    this->fromJson(json);
}

SWGSensorsInfraredValue::SWGSensorsInfraredValue() {
    init();
}

SWGSensorsInfraredValue::~SWGSensorsInfraredValue() {
    this->cleanup();
}

void
SWGSensorsInfraredValue::init() {
    infrared = new QList<SWGSensorsInfraredInfo*>();
    m_infrared_isSet = false;
}

void
SWGSensorsInfraredValue::cleanup() {
    if(infrared != nullptr) { 
        auto arr = infrared;
        for(auto o: *arr) { 
            delete o;
        }
        delete infrared;
    }
}

SWGSensorsInfraredValue*
SWGSensorsInfraredValue::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGSensorsInfraredValue::fromJsonObject(QJsonObject pJson) {
    
    ::Swagger::setValue(&infrared, pJson["infrared"], "QList", "SWGSensorsInfraredInfo");
}

QString
SWGSensorsInfraredValue::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
SWGSensorsInfraredValue::asJsonObject() {
    QJsonObject obj;
    if(infrared->size() > 0){
        toJsonArray((QList<void*>*)infrared, obj, "infrared", "SWGSensorsInfraredInfo");
    }

    return obj;
}

QList<SWGSensorsInfraredInfo*>*
SWGSensorsInfraredValue::getInfrared() {
    return infrared;
}
void
SWGSensorsInfraredValue::setInfrared(QList<SWGSensorsInfraredInfo*>* infrared) {
    this->infrared = infrared;
    this->m_infrared_isSet = true;
}


bool
SWGSensorsInfraredValue::isSet(){
    bool isObjectUpdated = false;
    do{
        if(infrared->size() > 0){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

