/**
 * Yanshee RESTful API
 *  ## 概述 Yanshee RESTful APIs是由使用[swagger-codegen](https://github.com/swagger-api/swagger-codegen)基于 [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki)的工程。 所有的API由Flask的[Connexion](https://github.com/zalando/connexion)来解释。 Yanshee-ROS中的apollo提供所有的RESTful APIs服务。 同时Yanshee RESTful APIs提供英文和中文两个版本： - [英文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [中文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## 依赖 Python 2.7 or 3.4+  
 *
 * OpenAPI spec version: 1.0.1
 * Contact: swenggroup@ubtrobot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGSubscriptionsVisionsDelete.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGSubscriptionsVisionsDelete::SWGSubscriptionsVisionsDelete(QString json) {
    init();
    this->fromJson(json);
}

SWGSubscriptionsVisionsDelete::SWGSubscriptionsVisionsDelete() {
    init();
}

SWGSubscriptionsVisionsDelete::~SWGSubscriptionsVisionsDelete() {
    this->cleanup();
}

void
SWGSubscriptionsVisionsDelete::init() {
    type = new QString("");
    m_type_isSet = false;
    url = new QString("");
    m_url_isSet = false;
}

void
SWGSubscriptionsVisionsDelete::cleanup() {
    if(type != nullptr) { 
        delete type;
    }
    if(url != nullptr) { 
        delete url;
    }
}

SWGSubscriptionsVisionsDelete*
SWGSubscriptionsVisionsDelete::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGSubscriptionsVisionsDelete::fromJsonObject(QJsonObject pJson) {
    ::Swagger::setValue(&type, pJson["type"], "QString", "QString");
    
    ::Swagger::setValue(&url, pJson["url"], "QString", "QString");
    
}

QString
SWGSubscriptionsVisionsDelete::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
SWGSubscriptionsVisionsDelete::asJsonObject() {
    QJsonObject obj;
    if(type != nullptr && *type != QString("")){
        toJsonValue(QString("type"), type, obj, QString("QString"));
    }
    if(url != nullptr && *url != QString("")){
        toJsonValue(QString("url"), url, obj, QString("QString"));
    }

    return obj;
}

QString*
SWGSubscriptionsVisionsDelete::getType() {
    return type;
}
void
SWGSubscriptionsVisionsDelete::setType(QString* type) {
    this->type = type;
    this->m_type_isSet = true;
}

QString*
SWGSubscriptionsVisionsDelete::getUrl() {
    return url;
}
void
SWGSubscriptionsVisionsDelete::setUrl(QString* url) {
    this->url = url;
    this->m_url_isSet = true;
}


bool
SWGSubscriptionsVisionsDelete::isSet(){
    bool isObjectUpdated = false;
    do{
        if(type != nullptr && *type != QString("")){ isObjectUpdated = true; break;}
        if(url != nullptr && *url != QString("")){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

