/**
 * Yanshee RESTful API
 *  ## 概述 Yanshee RESTful APIs是由使用[swagger-codegen](https://github.com/swagger-api/swagger-codegen)基于 [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki)的工程。 所有的API由Flask的[Connexion](https://github.com/zalando/connexion)来解释。 Yanshee-ROS中的apollo提供所有的RESTful APIs服务。 同时Yanshee RESTful APIs提供英文和中文两个版本： - [英文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [中文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## 依赖 Python 2.7 or 3.4+  
 *
 * OpenAPI spec version: 1.0.1
 * Contact: swenggroup@ubtrobot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGSensorsGyroValue.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGSensorsGyroValue::SWGSensorsGyroValue(QString json) {
    init();
    this->fromJson(json);
}

SWGSensorsGyroValue::SWGSensorsGyroValue() {
    init();
}

SWGSensorsGyroValue::~SWGSensorsGyroValue() {
    this->cleanup();
}

void
SWGSensorsGyroValue::init() {
    gyro = new QList<SWGSensorsGyroInfo*>();
    m_gyro_isSet = false;
}

void
SWGSensorsGyroValue::cleanup() {
    if(gyro != nullptr) { 
        auto arr = gyro;
        for(auto o: *arr) { 
            delete o;
        }
        delete gyro;
    }
}

SWGSensorsGyroValue*
SWGSensorsGyroValue::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGSensorsGyroValue::fromJsonObject(QJsonObject pJson) {
    
    ::Swagger::setValue(&gyro, pJson["gyro"], "QList", "SWGSensorsGyroInfo");
}

QString
SWGSensorsGyroValue::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
SWGSensorsGyroValue::asJsonObject() {
    QJsonObject obj;
    if(gyro->size() > 0){
        toJsonArray((QList<void*>*)gyro, obj, "gyro", "SWGSensorsGyroInfo");
    }

    return obj;
}

QList<SWGSensorsGyroInfo*>*
SWGSensorsGyroValue::getGyro() {
    return gyro;
}
void
SWGSensorsGyroValue::setGyro(QList<SWGSensorsGyroInfo*>* gyro) {
    this->gyro = gyro;
    this->m_gyro_isSet = true;
}


bool
SWGSensorsGyroValue::isSet(){
    bool isObjectUpdated = false;
    do{
        if(gyro->size() > 0){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

