/**
 * Yanshee RESTful API
 *  ## 概述 Yanshee RESTful APIs是由使用[swagger-codegen](https://github.com/swagger-api/swagger-codegen)基于 [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki)的工程。 所有的API由Flask的[Connexion](https://github.com/zalando/connexion)来解释。 Yanshee-ROS中的apollo提供所有的RESTful APIs服务。 同时Yanshee RESTful APIs提供英文和中文两个版本： - [英文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [中文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## 依赖 Python 2.7 or 3.4+  
 *
 * OpenAPI spec version: 1.0.1
 * Contact: swenggroup@ubtrobot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGServosMode.h
 *
 * 
 */

#ifndef SWGServosMode_H_
#define SWGServosMode_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"

namespace Swagger {

class SWGServosMode: public SWGObject {
public:
    SWGServosMode();
    SWGServosMode(QString json);
    ~SWGServosMode();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    SWGServosMode* fromJson(QString jsonString) override;

    QString* getRightShoulderRoll();
    void setRightShoulderRoll(QString* right_shoulder_roll);

    QString* getRightShoulderFlex();
    void setRightShoulderFlex(QString* right_shoulder_flex);

    QString* getRightElbowFlex();
    void setRightElbowFlex(QString* right_elbow_flex);

    QString* getLeftShoulderRoll();
    void setLeftShoulderRoll(QString* left_shoulder_roll);

    QString* getLeftShoulderFlex();
    void setLeftShoulderFlex(QString* left_shoulder_flex);

    QString* getLeftElbowFlex();
    void setLeftElbowFlex(QString* left_elbow_flex);

    QString* getRightHipLr();
    void setRightHipLr(QString* right_hip_lr);

    QString* getRightHipFb();
    void setRightHipFb(QString* right_hip_fb);

    QString* getRightKneeFlex();
    void setRightKneeFlex(QString* right_knee_flex);

    QString* getRightAnkleFb();
    void setRightAnkleFb(QString* right_ankle_fb);

    QString* getRightAnkleUd();
    void setRightAnkleUd(QString* right_ankle_ud);

    QString* getLeftHipLr();
    void setLeftHipLr(QString* left_hip_lr);

    QString* getLeftHipFb();
    void setLeftHipFb(QString* left_hip_fb);

    QString* getLeftKneeFlex();
    void setLeftKneeFlex(QString* left_knee_flex);

    QString* getLeftAnkleFb();
    void setLeftAnkleFb(QString* left_ankle_fb);

    QString* getLeftAnkleUd();
    void setLeftAnkleUd(QString* left_ankle_ud);

    QString* getNeckLr();
    void setNeckLr(QString* neck_lr);


    virtual bool isSet() override;

private:
    QString* right_shoulder_roll;
    bool m_right_shoulder_roll_isSet;

    QString* right_shoulder_flex;
    bool m_right_shoulder_flex_isSet;

    QString* right_elbow_flex;
    bool m_right_elbow_flex_isSet;

    QString* left_shoulder_roll;
    bool m_left_shoulder_roll_isSet;

    QString* left_shoulder_flex;
    bool m_left_shoulder_flex_isSet;

    QString* left_elbow_flex;
    bool m_left_elbow_flex_isSet;

    QString* right_hip_lr;
    bool m_right_hip_lr_isSet;

    QString* right_hip_fb;
    bool m_right_hip_fb_isSet;

    QString* right_knee_flex;
    bool m_right_knee_flex_isSet;

    QString* right_ankle_fb;
    bool m_right_ankle_fb_isSet;

    QString* right_ankle_ud;
    bool m_right_ankle_ud_isSet;

    QString* left_hip_lr;
    bool m_left_hip_lr_isSet;

    QString* left_hip_fb;
    bool m_left_hip_fb_isSet;

    QString* left_knee_flex;
    bool m_left_knee_flex_isSet;

    QString* left_ankle_fb;
    bool m_left_ankle_fb_isSet;

    QString* left_ankle_ud;
    bool m_left_ankle_ud_isSet;

    QString* neck_lr;
    bool m_neck_lr_isSet;

};

}

#endif /* SWGServosMode_H_ */
