/**
 * Yanshee RESTful API
 *  ## 概述 Yanshee RESTful APIs是由使用[swagger-codegen](https://github.com/swagger-api/swagger-codegen)基于 [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki)的工程。 所有的API由Flask的[Connexion](https://github.com/zalando/connexion)来解释。 Yanshee-ROS中的apollo提供所有的RESTful APIs服务。 同时Yanshee RESTful APIs提供英文和中文两个版本： - [英文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [中文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## 依赖 Python 2.7 or 3.4+  
 *
 * OpenAPI spec version: 1.0.1
 * Contact: swenggroup@ubtrobot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGSensorsEnvironmentValue.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGSensorsEnvironmentValue::SWGSensorsEnvironmentValue(QString json) {
    init();
    this->fromJson(json);
}

SWGSensorsEnvironmentValue::SWGSensorsEnvironmentValue() {
    init();
}

SWGSensorsEnvironmentValue::~SWGSensorsEnvironmentValue() {
    this->cleanup();
}

void
SWGSensorsEnvironmentValue::init() {
    environment = new QList<SWGSensorsEnvironmentInfo*>();
    m_environment_isSet = false;
}

void
SWGSensorsEnvironmentValue::cleanup() {
    if(environment != nullptr) { 
        auto arr = environment;
        for(auto o: *arr) { 
            delete o;
        }
        delete environment;
    }
}

SWGSensorsEnvironmentValue*
SWGSensorsEnvironmentValue::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGSensorsEnvironmentValue::fromJsonObject(QJsonObject pJson) {
    
    ::Swagger::setValue(&environment, pJson["environment"], "QList", "SWGSensorsEnvironmentInfo");
}

QString
SWGSensorsEnvironmentValue::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
SWGSensorsEnvironmentValue::asJsonObject() {
    QJsonObject obj;
    if(environment->size() > 0){
        toJsonArray((QList<void*>*)environment, obj, "environment", "SWGSensorsEnvironmentInfo");
    }

    return obj;
}

QList<SWGSensorsEnvironmentInfo*>*
SWGSensorsEnvironmentValue::getEnvironment() {
    return environment;
}
void
SWGSensorsEnvironmentValue::setEnvironment(QList<SWGSensorsEnvironmentInfo*>* environment) {
    this->environment = environment;
    this->m_environment_isSet = true;
}


bool
SWGSensorsEnvironmentValue::isSet(){
    bool isObjectUpdated = false;
    do{
        if(environment->size() > 0){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

