/**
 * Yanshee RESTful API
 *  ## 概述 Yanshee RESTful APIs是由使用[swagger-codegen](https://github.com/swagger-api/swagger-codegen)基于 [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki)的工程。 所有的API由Flask的[Connexion](https://github.com/zalando/connexion)来解释。 Yanshee-ROS中的apollo提供所有的RESTful APIs服务。 同时Yanshee RESTful APIs提供英文和中文两个版本： - [英文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [中文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## 依赖 Python 2.7 or 3.4+  
 *
 * OpenAPI spec version: 1.0.1
 * Contact: swenggroup@ubtrobot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGSensorsParameter.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGSensorsParameter::SWGSensorsParameter(QString json) {
    init();
    this->fromJson(json);
}

SWGSensorsParameter::SWGSensorsParameter() {
    init();
}

SWGSensorsParameter::~SWGSensorsParameter() {
    this->cleanup();
}

void
SWGSensorsParameter::init() {
    type = new QString("");
    m_type_isSet = false;
    id = 0;
    m_id_isSet = false;
    value = 0;
    m_value_isSet = false;
}

void
SWGSensorsParameter::cleanup() {
    if(type != nullptr) { 
        delete type;
    }


}

SWGSensorsParameter*
SWGSensorsParameter::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGSensorsParameter::fromJsonObject(QJsonObject pJson) {
    ::Swagger::setValue(&type, pJson["type"], "QString", "QString");
    
    ::Swagger::setValue(&id, pJson["id"], "qint32", "");
    
    ::Swagger::setValue(&value, pJson["value"], "qint32", "");
    
}

QString
SWGSensorsParameter::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
SWGSensorsParameter::asJsonObject() {
    QJsonObject obj;
    if(type != nullptr && *type != QString("")){
        toJsonValue(QString("type"), type, obj, QString("QString"));
    }
    if(m_id_isSet){
        obj.insert("id", QJsonValue(id));
    }
    if(m_value_isSet){
        obj.insert("value", QJsonValue(value));
    }

    return obj;
}

QString*
SWGSensorsParameter::getType() {
    return type;
}
void
SWGSensorsParameter::setType(QString* type) {
    this->type = type;
    this->m_type_isSet = true;
}

qint32
SWGSensorsParameter::getId() {
    return id;
}
void
SWGSensorsParameter::setId(qint32 id) {
    this->id = id;
    this->m_id_isSet = true;
}

qint32
SWGSensorsParameter::getValue() {
    return value;
}
void
SWGSensorsParameter::setValue(qint32 value) {
    this->value = value;
    this->m_value_isSet = true;
}


bool
SWGSensorsParameter::isSet(){
    bool isObjectUpdated = false;
    do{
        if(type != nullptr && *type != QString("")){ isObjectUpdated = true; break;}
        if(m_id_isSet){ isObjectUpdated = true; break;}
        if(m_value_isSet){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

