/**
 * Yanshee RESTful API
 *  ## 概述 Yanshee RESTful APIs是由使用[swagger-codegen](https://github.com/swagger-api/swagger-codegen)基于 [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki)的工程。 所有的API由Flask的[Connexion](https://github.com/zalando/connexion)来解释。 Yanshee-ROS中的apollo提供所有的RESTful APIs服务。 同时Yanshee RESTful APIs提供英文和中文两个版本： - [英文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [中文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## 依赖 Python 2.7 or 3.4+  
 *
 * OpenAPI spec version: 1.0.1
 * Contact: swenggroup@ubtrobot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGServosAngles.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGServosAngles::SWGServosAngles(QString json) {
    init();
    this->fromJson(json);
}

SWGServosAngles::SWGServosAngles() {
    init();
}

SWGServosAngles::~SWGServosAngles() {
    this->cleanup();
}

void
SWGServosAngles::init() {
    right_shoulder_roll = 0;
    m_right_shoulder_roll_isSet = false;
    right_shoulder_flex = 0;
    m_right_shoulder_flex_isSet = false;
    right_elbow_flex = 0;
    m_right_elbow_flex_isSet = false;
    left_shoulder_roll = 0;
    m_left_shoulder_roll_isSet = false;
    left_shoulder_flex = 0;
    m_left_shoulder_flex_isSet = false;
    left_elbow_flex = 0;
    m_left_elbow_flex_isSet = false;
    right_hip_lr = 0;
    m_right_hip_lr_isSet = false;
    right_hip_fb = 0;
    m_right_hip_fb_isSet = false;
    right_knee_flex = 0;
    m_right_knee_flex_isSet = false;
    right_ankle_fb = 0;
    m_right_ankle_fb_isSet = false;
    right_ankle_ud = 0;
    m_right_ankle_ud_isSet = false;
    left_hip_lr = 0;
    m_left_hip_lr_isSet = false;
    left_hip_fb = 0;
    m_left_hip_fb_isSet = false;
    left_knee_flex = 0;
    m_left_knee_flex_isSet = false;
    left_ankle_fb = 0;
    m_left_ankle_fb_isSet = false;
    left_ankle_ud = 0;
    m_left_ankle_ud_isSet = false;
    neck_lr = 0;
    m_neck_lr_isSet = false;
}

void
SWGServosAngles::cleanup() {

















}

SWGServosAngles*
SWGServosAngles::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

//added 2020-12-17
void SWGServosAngles::setIsSetFlag(const QJsonObject& obj)
{
    if(obj.contains("RightShoulderRoll")) { m_right_shoulder_roll_isSet = true; }
    if(obj.contains("RightShoulderFlex")) { m_right_shoulder_flex_isSet = true; }
    if(obj.contains("RightElbowFlex"))    { m_right_elbow_flex_isSet = true; }
    if(obj.contains("LeftShoulderRoll"))  { m_left_shoulder_roll_isSet = true; }
    if(obj.contains("LeftShoulderFlex"))  { m_left_shoulder_flex_isSet = true; }
    if(obj.contains("LeftElbowFlex"))     { m_left_elbow_flex_isSet = true; }
    if(obj.contains("RightHipLR"))        { m_right_hip_lr_isSet = true; }
    if(obj.contains("RightHipFB"))        { m_right_hip_fb_isSet = true; }
    if(obj.contains("RightKneeFlex"))     { m_right_knee_flex_isSet = true; }
    if(obj.contains("RightAnkleFB"))      { m_right_ankle_fb_isSet = true; }
    if(obj.contains("RightAnkleUD"))      { m_right_ankle_ud_isSet = true; }
    if(obj.contains("LeftHipLR"))         { m_left_hip_lr_isSet = true; }
    if(obj.contains("LeftHipFB"))         { m_left_hip_fb_isSet = true; }
    if(obj.contains("LeftKneeFlex"))      { m_left_knee_flex_isSet = true; }
    if(obj.contains("LeftAnkleFB"))       { m_left_ankle_fb_isSet = true; }
    if(obj.contains("LeftAnkleUD"))       { m_left_ankle_ud_isSet = true; }
    if(obj.contains("NeckLR"))            { m_neck_lr_isSet = true; }
}

void
SWGServosAngles::fromJsonObject(QJsonObject pJson) {
    QJsonObject tempObj = pJson; //added 2020-12-17
    ::Swagger::setValue(&right_shoulder_roll, pJson["RightShoulderRoll"], "qint32", "");
    
    ::Swagger::setValue(&right_shoulder_flex, pJson["RightShoulderFlex"], "qint32", "");
    
    ::Swagger::setValue(&right_elbow_flex, pJson["RightElbowFlex"], "qint32", "");
    
    ::Swagger::setValue(&left_shoulder_roll, pJson["LeftShoulderRoll"], "qint32", "");
    
    ::Swagger::setValue(&left_shoulder_flex, pJson["LeftShoulderFlex"], "qint32", "");
    
    ::Swagger::setValue(&left_elbow_flex, pJson["LeftElbowFlex"], "qint32", "");
    
    ::Swagger::setValue(&right_hip_lr, pJson["RightHipLR"], "qint32", "");
    
    ::Swagger::setValue(&right_hip_fb, pJson["RightHipFB"], "qint32", "");
    
    ::Swagger::setValue(&right_knee_flex, pJson["RightKneeFlex"], "qint32", "");
    
    ::Swagger::setValue(&right_ankle_fb, pJson["RightAnkleFB"], "qint32", "");
    
    ::Swagger::setValue(&right_ankle_ud, pJson["RightAnkleUD"], "qint32", "");
    
    ::Swagger::setValue(&left_hip_lr, pJson["LeftHipLR"], "qint32", "");
    
    ::Swagger::setValue(&left_hip_fb, pJson["LeftHipFB"], "qint32", "");
    
    ::Swagger::setValue(&left_knee_flex, pJson["LeftKneeFlex"], "qint32", "");
    
    ::Swagger::setValue(&left_ankle_fb, pJson["LeftAnkleFB"], "qint32", "");
    
    ::Swagger::setValue(&left_ankle_ud, pJson["LeftAnkleUD"], "qint32", "");
    
    ::Swagger::setValue(&neck_lr, pJson["NeckLR"], "qint32", "");
    
    setIsSetFlag(tempObj); //added 2020-12-17
}

QString
SWGServosAngles::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
SWGServosAngles::asJsonObject() {
    QJsonObject obj;
    if(m_right_shoulder_roll_isSet){
        obj.insert("RightShoulderRoll", QJsonValue(right_shoulder_roll));
    }
    if(m_right_shoulder_flex_isSet){
        obj.insert("RightShoulderFlex", QJsonValue(right_shoulder_flex));
    }
    if(m_right_elbow_flex_isSet){
        obj.insert("RightElbowFlex", QJsonValue(right_elbow_flex));
    }
    if(m_left_shoulder_roll_isSet){
        obj.insert("LeftShoulderRoll", QJsonValue(left_shoulder_roll));
    }
    if(m_left_shoulder_flex_isSet){
        obj.insert("LeftShoulderFlex", QJsonValue(left_shoulder_flex));
    }
    if(m_left_elbow_flex_isSet){
        obj.insert("LeftElbowFlex", QJsonValue(left_elbow_flex));
    }
    if(m_right_hip_lr_isSet){
        obj.insert("RightHipLR", QJsonValue(right_hip_lr));
    }
    if(m_right_hip_fb_isSet){
        obj.insert("RightHipFB", QJsonValue(right_hip_fb));
    }
    if(m_right_knee_flex_isSet){
        obj.insert("RightKneeFlex", QJsonValue(right_knee_flex));
    }
    if(m_right_ankle_fb_isSet){
        obj.insert("RightAnkleFB", QJsonValue(right_ankle_fb));
    }
    if(m_right_ankle_ud_isSet){
        obj.insert("RightAnkleUD", QJsonValue(right_ankle_ud));
    }
    if(m_left_hip_lr_isSet){
        obj.insert("LeftHipLR", QJsonValue(left_hip_lr));
    }
    if(m_left_hip_fb_isSet){
        obj.insert("LeftHipFB", QJsonValue(left_hip_fb));
    }
    if(m_left_knee_flex_isSet){
        obj.insert("LeftKneeFlex", QJsonValue(left_knee_flex));
    }
    if(m_left_ankle_fb_isSet){
        obj.insert("LeftAnkleFB", QJsonValue(left_ankle_fb));
    }
    if(m_left_ankle_ud_isSet){
        obj.insert("LeftAnkleUD", QJsonValue(left_ankle_ud));
    }
    if(m_neck_lr_isSet){
        obj.insert("NeckLR", QJsonValue(neck_lr));
    }

    return obj;
}

qint32
SWGServosAngles::getRightShoulderRoll() {
    return right_shoulder_roll;
}
void
SWGServosAngles::setRightShoulderRoll(qint32 right_shoulder_roll) {
    this->right_shoulder_roll = right_shoulder_roll;
    this->m_right_shoulder_roll_isSet = true;
}

qint32
SWGServosAngles::getRightShoulderFlex() {
    return right_shoulder_flex;
}
void
SWGServosAngles::setRightShoulderFlex(qint32 right_shoulder_flex) {
    this->right_shoulder_flex = right_shoulder_flex;
    this->m_right_shoulder_flex_isSet = true;
}

qint32
SWGServosAngles::getRightElbowFlex() {
    return right_elbow_flex;
}
void
SWGServosAngles::setRightElbowFlex(qint32 right_elbow_flex) {
    this->right_elbow_flex = right_elbow_flex;
    this->m_right_elbow_flex_isSet = true;
}

qint32
SWGServosAngles::getLeftShoulderRoll() {
    return left_shoulder_roll;
}
void
SWGServosAngles::setLeftShoulderRoll(qint32 left_shoulder_roll) {
    this->left_shoulder_roll = left_shoulder_roll;
    this->m_left_shoulder_roll_isSet = true;
}

qint32
SWGServosAngles::getLeftShoulderFlex() {
    return left_shoulder_flex;
}
void
SWGServosAngles::setLeftShoulderFlex(qint32 left_shoulder_flex) {
    this->left_shoulder_flex = left_shoulder_flex;
    this->m_left_shoulder_flex_isSet = true;
}

qint32
SWGServosAngles::getLeftElbowFlex() {
    return left_elbow_flex;
}
void
SWGServosAngles::setLeftElbowFlex(qint32 left_elbow_flex) {
    this->left_elbow_flex = left_elbow_flex;
    this->m_left_elbow_flex_isSet = true;
}

qint32
SWGServosAngles::getRightHipLr() {
    return right_hip_lr;
}
void
SWGServosAngles::setRightHipLr(qint32 right_hip_lr) {
    this->right_hip_lr = right_hip_lr;
    this->m_right_hip_lr_isSet = true;
}

qint32
SWGServosAngles::getRightHipFb() {
    return right_hip_fb;
}
void
SWGServosAngles::setRightHipFb(qint32 right_hip_fb) {
    this->right_hip_fb = right_hip_fb;
    this->m_right_hip_fb_isSet = true;
}

qint32
SWGServosAngles::getRightKneeFlex() {
    return right_knee_flex;
}
void
SWGServosAngles::setRightKneeFlex(qint32 right_knee_flex) {
    this->right_knee_flex = right_knee_flex;
    this->m_right_knee_flex_isSet = true;
}

qint32
SWGServosAngles::getRightAnkleFb() {
    return right_ankle_fb;
}
void
SWGServosAngles::setRightAnkleFb(qint32 right_ankle_fb) {
    this->right_ankle_fb = right_ankle_fb;
    this->m_right_ankle_fb_isSet = true;
}

qint32
SWGServosAngles::getRightAnkleUd() {
    return right_ankle_ud;
}
void
SWGServosAngles::setRightAnkleUd(qint32 right_ankle_ud) {
    this->right_ankle_ud = right_ankle_ud;
    this->m_right_ankle_ud_isSet = true;
}

qint32
SWGServosAngles::getLeftHipLr() {
    return left_hip_lr;
}
void
SWGServosAngles::setLeftHipLr(qint32 left_hip_lr) {
    this->left_hip_lr = left_hip_lr;
    this->m_left_hip_lr_isSet = true;
}

qint32
SWGServosAngles::getLeftHipFb() {
    return left_hip_fb;
}
void
SWGServosAngles::setLeftHipFb(qint32 left_hip_fb) {
    this->left_hip_fb = left_hip_fb;
    this->m_left_hip_fb_isSet = true;
}

qint32
SWGServosAngles::getLeftKneeFlex() {
    return left_knee_flex;
}
void
SWGServosAngles::setLeftKneeFlex(qint32 left_knee_flex) {
    this->left_knee_flex = left_knee_flex;
    this->m_left_knee_flex_isSet = true;
}

qint32
SWGServosAngles::getLeftAnkleFb() {
    return left_ankle_fb;
}
void
SWGServosAngles::setLeftAnkleFb(qint32 left_ankle_fb) {
    this->left_ankle_fb = left_ankle_fb;
    this->m_left_ankle_fb_isSet = true;
}

qint32
SWGServosAngles::getLeftAnkleUd() {
    return left_ankle_ud;
}
void
SWGServosAngles::setLeftAnkleUd(qint32 left_ankle_ud) {
    this->left_ankle_ud = left_ankle_ud;
    this->m_left_ankle_ud_isSet = true;
}

qint32
SWGServosAngles::getNeckLr() {
    return neck_lr;
}
void
SWGServosAngles::setNeckLr(qint32 neck_lr) {
    this->neck_lr = neck_lr;
    this->m_neck_lr_isSet = true;
}


bool
SWGServosAngles::isSet(){
    bool isObjectUpdated = false;
    do{
        if(m_right_shoulder_roll_isSet){ isObjectUpdated = true; break;}
        if(m_right_shoulder_flex_isSet){ isObjectUpdated = true; break;}
        if(m_right_elbow_flex_isSet){ isObjectUpdated = true; break;}
        if(m_left_shoulder_roll_isSet){ isObjectUpdated = true; break;}
        if(m_left_shoulder_flex_isSet){ isObjectUpdated = true; break;}
        if(m_left_elbow_flex_isSet){ isObjectUpdated = true; break;}
        if(m_right_hip_lr_isSet){ isObjectUpdated = true; break;}
        if(m_right_hip_fb_isSet){ isObjectUpdated = true; break;}
        if(m_right_knee_flex_isSet){ isObjectUpdated = true; break;}
        if(m_right_ankle_fb_isSet){ isObjectUpdated = true; break;}
        if(m_right_ankle_ud_isSet){ isObjectUpdated = true; break;}
        if(m_left_hip_lr_isSet){ isObjectUpdated = true; break;}
        if(m_left_hip_fb_isSet){ isObjectUpdated = true; break;}
        if(m_left_knee_flex_isSet){ isObjectUpdated = true; break;}
        if(m_left_ankle_fb_isSet){ isObjectUpdated = true; break;}
        if(m_left_ankle_ud_isSet){ isObjectUpdated = true; break;}
        if(m_neck_lr_isSet){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

