/**
 * Yanshee RESTful API
 *  ## 概述 Yanshee RESTful APIs是由使用[swagger-codegen](https://github.com/swagger-api/swagger-codegen)基于 [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki)的工程。 所有的API由Flask的[Connexion](https://github.com/zalando/connexion)来解释。 Yanshee-ROS中的apollo提供所有的RESTful APIs服务。 同时Yanshee RESTful APIs提供英文和中文两个版本： - [英文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [中文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## 依赖 Python 2.7 or 3.4+  
 *
 * OpenAPI spec version: 1.0.1
 * Contact: swenggroup@ubtrobot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGTotalTime.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGTotalTime::SWGTotalTime(QString json) {
    init();
    this->fromJson(json);
}

SWGTotalTime::SWGTotalTime() {
    init();
}

SWGTotalTime::~SWGTotalTime() {
    this->cleanup();
}

void
SWGTotalTime::init() {
    total_time = 0;
    m_total_time_isSet = false;
}

void
SWGTotalTime::cleanup() {

}

SWGTotalTime*
SWGTotalTime::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGTotalTime::fromJsonObject(QJsonObject pJson) {
    ::Swagger::setValue(&total_time, pJson["total_time"], "qint32", "");
    
}

QString
SWGTotalTime::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
SWGTotalTime::asJsonObject() {
    QJsonObject obj;
    if(m_total_time_isSet){
        obj.insert("total_time", QJsonValue(total_time));
    }

    return obj;
}

qint32
SWGTotalTime::getTotalTime() {
    return total_time;
}
void
SWGTotalTime::setTotalTime(qint32 total_time) {
    this->total_time = total_time;
    this->m_total_time_isSet = true;
}


bool
SWGTotalTime::isSet(){
    bool isObjectUpdated = false;
    do{
        if(m_total_time_isSet){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

