/**
 * Yanshee RESTful API
 *  ## 概述 Yanshee RESTful APIs是由使用[swagger-codegen](https://github.com/swagger-api/swagger-codegen)基于 [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki)的工程。 所有的API由Flask的[Connexion](https://github.com/zalando/connexion)来解释。 Yanshee-ROS中的apollo提供所有的RESTful APIs服务。 同时Yanshee RESTful APIs提供英文和中文两个版本： - [英文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [中文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## 依赖 Python 2.7 or 3.4+  
 *
 * OpenAPI spec version: 1.0.1
 * Contact: swenggroup@ubtrobot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGVisionsQuantity.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGVisionsQuantity::SWGVisionsQuantity(QString json) {
    init();
    this->fromJson(json);
}

SWGVisionsQuantity::SWGVisionsQuantity() {
    init();
}

SWGVisionsQuantity::~SWGVisionsQuantity() {
    this->cleanup();
}

void
SWGVisionsQuantity::init() {
    quantity = 0;
    m_quantity_isSet = false;
}

void
SWGVisionsQuantity::cleanup() {

}

SWGVisionsQuantity*
SWGVisionsQuantity::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGVisionsQuantity::fromJsonObject(QJsonObject pJson) {
    ::Swagger::setValue(&quantity, pJson["quantity"], "qint32", "");
    
}

QString
SWGVisionsQuantity::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
SWGVisionsQuantity::asJsonObject() {
    QJsonObject obj;
    if(m_quantity_isSet){
        obj.insert("quantity", QJsonValue(quantity));
    }

    return obj;
}

qint32
SWGVisionsQuantity::getQuantity() {
    return quantity;
}
void
SWGVisionsQuantity::setQuantity(qint32 quantity) {
    this->quantity = quantity;
    this->m_quantity_isSet = true;
}


bool
SWGVisionsQuantity::isSet(){
    bool isObjectUpdated = false;
    do{
        if(m_quantity_isSet){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

