/**
 * Yanshee RESTful API
 *  ## 概述 Yanshee RESTful APIs是由使用[swagger-codegen](https://github.com/swagger-api/swagger-codegen)基于 [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki)的工程。 所有的API由Flask的[Connexion](https://github.com/zalando/connexion)来解释。 Yanshee-ROS中的apollo提供所有的RESTful APIs服务。 同时Yanshee RESTful APIs提供英文和中文两个版本： - [英文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [中文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## 依赖 Python 2.7 or 3.4+  
 *
 * OpenAPI spec version: 1.0.1
 * Contact: swenggroup@ubtrobot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGVoiceOfflineSyntaxRule.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGVoiceOfflineSyntaxRule::SWGVoiceOfflineSyntaxRule(QString json) {
    init();
    this->fromJson(json);
}

SWGVoiceOfflineSyntaxRule::SWGVoiceOfflineSyntaxRule() {
    init();
}

SWGVoiceOfflineSyntaxRule::~SWGVoiceOfflineSyntaxRule() {
    this->cleanup();
}

void
SWGVoiceOfflineSyntaxRule::init() {
    name = new QString("");
    m_name_isSet = false;
    value = new QString("");
    m_value_isSet = false;
}

void
SWGVoiceOfflineSyntaxRule::cleanup() {
    if(name != nullptr) { 
        delete name;
    }
    if(value != nullptr) { 
        delete value;
    }
}

SWGVoiceOfflineSyntaxRule*
SWGVoiceOfflineSyntaxRule::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGVoiceOfflineSyntaxRule::fromJsonObject(QJsonObject pJson) {
    ::Swagger::setValue(&name, pJson["name"], "QString", "QString");
    
    ::Swagger::setValue(&value, pJson["value"], "QString", "QString");
    
}

QString
SWGVoiceOfflineSyntaxRule::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
SWGVoiceOfflineSyntaxRule::asJsonObject() {
    QJsonObject obj;
    if(name != nullptr && *name != QString("")){
        toJsonValue(QString("name"), name, obj, QString("QString"));
    }
    if(value != nullptr && *value != QString("")){
        toJsonValue(QString("value"), value, obj, QString("QString"));
    }

    return obj;
}

QString*
SWGVoiceOfflineSyntaxRule::getName() {
    return name;
}
void
SWGVoiceOfflineSyntaxRule::setName(QString* name) {
    this->name = name;
    this->m_name_isSet = true;
}

QString*
SWGVoiceOfflineSyntaxRule::getValue() {
    return value;
}
void
SWGVoiceOfflineSyntaxRule::setValue(QString* value) {
    this->value = value;
    this->m_value_isSet = true;
}


bool
SWGVoiceOfflineSyntaxRule::isSet(){
    bool isObjectUpdated = false;
    do{
        if(name != nullptr && *name != QString("")){ isObjectUpdated = true; break;}
        if(value != nullptr && *value != QString("")){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

