#ifndef BEHAVIORTABLE_GLOBAL_H
#define BEHAVIORTABLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BEHAVIORTABLE_LIBRARY)
#  define BEHAVIORTABLE_EXPORT Q_DECL_EXPORT
#else
#  define BEHAVIORTABLE_EXPORT Q_DECL_IMPORT
#endif

#endif // BEHAVIORTABLE_GLOBAL_H
