/**
 * Yanshee RESTful API
 *  ## 概述 Yanshee RESTful APIs是由使用[swagger-codegen](https://github.com/swagger-api/swagger-codegen)基于 [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki)的工程。 所有的API由Flask的[Connexion](https://github.com/zalando/connexion)来解释。 Yanshee-ROS中的apollo提供所有的RESTful APIs服务。 同时Yanshee RESTful APIs提供英文和中文两个版本： - [英文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [中文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## 依赖 Python 2.7 or 3.4+  
 *
 * OpenAPI spec version: 1.0.0
 * Contact: swenggroup@ubtrobot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGDevicesLanguage.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGDevicesLanguage::SWGDevicesLanguage(QString json) {
    init();
    this->fromJson(json);
}

SWGDevicesLanguage::SWGDevicesLanguage() {
    init();
}

SWGDevicesLanguage::~SWGDevicesLanguage() {
    this->cleanup();
}

void
SWGDevicesLanguage::init() {
    language = new QString("");
    m_language_isSet = false;
}

void
SWGDevicesLanguage::cleanup() {
    if(language != nullptr) { 
        delete language;
    }
}

SWGDevicesLanguage*
SWGDevicesLanguage::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGDevicesLanguage::fromJsonObject(QJsonObject pJson) {
    ::Swagger::setValue(&language, pJson["language"], "QString", "QString");
    
}

QString
SWGDevicesLanguage::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
SWGDevicesLanguage::asJsonObject() {
    QJsonObject obj;
    if(language != nullptr && *language != QString("")){
        toJsonValue(QString("language"), language, obj, QString("QString"));
    }

    return obj;
}

QString*
SWGDevicesLanguage::getLanguage() {
    return language;
}
void
SWGDevicesLanguage::setLanguage(QString* language) {
    this->language = language;
    this->m_language_isSet = true;
}


bool
SWGDevicesLanguage::isSet(){
    bool isObjectUpdated = false;
    do{
        if(language != nullptr && *language != QString("")){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

