/**
 * Yanshee RESTful API
 *  ## 概述 Yanshee RESTful APIs是由使用[swagger-codegen](https://github.com/swagger-api/swagger-codegen)基于 [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki)的工程。 所有的API由Flask的[Connexion](https://github.com/zalando/connexion)来解释。 Yanshee-ROS中的apollo提供所有的RESTful APIs服务。 同时Yanshee RESTful APIs提供英文和中文两个版本： - [英文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [中文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## 依赖 Python 2.7 or 3.4+  
 *
 * OpenAPI spec version: 1.0.0
 * Contact: swenggroup@ubtrobot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGDevicesBattery.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGDevicesBattery::SWGDevicesBattery(QString json) {
    init();
    this->fromJson(json);
}

SWGDevicesBattery::SWGDevicesBattery() {
    init();
}

SWGDevicesBattery::~SWGDevicesBattery() {
    this->cleanup();
}

void
SWGDevicesBattery::init() {
    voltage = 0;
    m_voltage_isSet = false;
    charging = 0;
    m_charging_isSet = false;
    percent = 0;
    m_percent_isSet = false;
}

void
SWGDevicesBattery::cleanup() {



}

SWGDevicesBattery*
SWGDevicesBattery::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGDevicesBattery::fromJsonObject(QJsonObject pJson) {
    ::Swagger::setValue(&voltage, pJson["voltage"], "qint32", "");
    
    ::Swagger::setValue(&charging, pJson["charging"], "qint32", "");
    
    ::Swagger::setValue(&percent, pJson["percent"], "qint32", "");
    
}

QString
SWGDevicesBattery::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
SWGDevicesBattery::asJsonObject() {
    QJsonObject obj;
    if(m_voltage_isSet){
        obj.insert("voltage", QJsonValue(voltage));
    }
    if(m_charging_isSet){
        obj.insert("charging", QJsonValue(charging));
    }
    if(m_percent_isSet){
        obj.insert("percent", QJsonValue(percent));
    }

    return obj;
}

qint32
SWGDevicesBattery::getVoltage() {
    return voltage;
}
void
SWGDevicesBattery::setVoltage(qint32 voltage) {
    this->voltage = voltage;
    this->m_voltage_isSet = true;
}

qint32
SWGDevicesBattery::getCharging() {
    return charging;
}
void
SWGDevicesBattery::setCharging(qint32 charging) {
    this->charging = charging;
    this->m_charging_isSet = true;
}

qint32
SWGDevicesBattery::getPercent() {
    return percent;
}
void
SWGDevicesBattery::setPercent(qint32 percent) {
    this->percent = percent;
    this->m_percent_isSet = true;
}


bool
SWGDevicesBattery::isSet(){
    bool isObjectUpdated = false;
    do{
        if(m_voltage_isSet){ isObjectUpdated = true; break;}
        if(m_charging_isSet){ isObjectUpdated = true; break;}
        if(m_percent_isSet){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

