/**
 * Yanshee RESTful API
 *  ## 概述 Yanshee RESTful APIs是由使用[swagger-codegen](https://github.com/swagger-api/swagger-codegen)基于 [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki)的工程。 所有的API由Flask的[Connexion](https://github.com/zalando/connexion)来解释。 Yanshee-ROS中的apollo提供所有的RESTful APIs服务。 同时Yanshee RESTful APIs提供英文和中文两个版本： - [英文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [中文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## 依赖 Python 2.7 or 3.4+  
 *
 * OpenAPI spec version: 1.0.0
 * Contact: swenggroup@ubtrobot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGDevicesVolume.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGDevicesVolume::SWGDevicesVolume(QString json) {
    init();
    this->fromJson(json);
}

SWGDevicesVolume::SWGDevicesVolume() {
    init();
}

SWGDevicesVolume::~SWGDevicesVolume() {
    this->cleanup();
}

void
SWGDevicesVolume::init() {
    volume = 0;
    m_volume_isSet = false;
}

void
SWGDevicesVolume::cleanup() {

}

SWGDevicesVolume*
SWGDevicesVolume::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGDevicesVolume::fromJsonObject(QJsonObject pJson) {
    ::Swagger::setValue(&volume, pJson["volume"], "qint32", "");
    
}

QString
SWGDevicesVolume::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
SWGDevicesVolume::asJsonObject() {
    QJsonObject obj;
    if(m_volume_isSet){
        obj.insert("volume", QJsonValue(volume));
    }

    return obj;
}

qint32
SWGDevicesVolume::getVolume() {
    return volume;
}
void
SWGDevicesVolume::setVolume(qint32 volume) {
    this->volume = volume;
    this->m_volume_isSet = true;
}


bool
SWGDevicesVolume::isSet(){
    bool isObjectUpdated = false;
    do{
        if(m_volume_isSet){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

