/**
 * Yanshee RESTful API
 *  ## 概述 Yanshee RESTful APIs是由使用[swagger-codegen](https://github.com/swagger-api/swagger-codegen)基于 [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki)的工程。 所有的API由Flask的[Connexion](https://github.com/zalando/connexion)来解释。 Yanshee-ROS中的apollo提供所有的RESTful APIs服务。 同时Yanshee RESTful APIs提供英文和中文两个版本： - [英文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [中文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## 依赖 Python 2.7 or 3.4+  
 *
 * OpenAPI spec version: 1.0.0
 * Contact: swenggroup@ubtrobot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGMotionsList.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGMotionsList::SWGMotionsList(QString json) {
    init();
    this->fromJson(json);
}

SWGMotionsList::SWGMotionsList() {
    init();
}

SWGMotionsList::~SWGMotionsList() {
    this->cleanup();
}

void
SWGMotionsList::init() {
    motions = new QList<SWGMotionsInfo*>();
    m_motions_isSet = false;
}

void
SWGMotionsList::cleanup() {
    if(motions != nullptr) { 
        auto arr = motions;
        for(auto o: *arr) { 
            delete o;
        }
        delete motions;
    }
}

SWGMotionsList*
SWGMotionsList::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGMotionsList::fromJsonObject(QJsonObject pJson) {
    
    ::Swagger::setValue(&motions, pJson["motions"], "QList", "SWGMotionsInfo");
}

QString
SWGMotionsList::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
SWGMotionsList::asJsonObject() {
    QJsonObject obj;
    if(motions->size() > 0){
        toJsonArray((QList<void*>*)motions, obj, "motions", "SWGMotionsInfo");
    }

    return obj;
}

QList<SWGMotionsInfo*>*
SWGMotionsList::getMotions() {
    return motions;
}
void
SWGMotionsList::setMotions(QList<SWGMotionsInfo*>* motions) {
    this->motions = motions;
    this->m_motions_isSet = true;
}


bool
SWGMotionsList::isSet(){
    bool isObjectUpdated = false;
    do{
        if(motions->size() > 0){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

