/**
 * Yanshee RESTful API
 *  ## 概述 Yanshee RESTful APIs是由使用[swagger-codegen](https://github.com/swagger-api/swagger-codegen)基于 [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki)的工程。 所有的API由Flask的[Connexion](https://github.com/zalando/connexion)来解释。 Yanshee-ROS中的apollo提供所有的RESTful APIs服务。 同时Yanshee RESTful APIs提供英文和中文两个版本： - [英文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [中文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## 依赖 Python 2.7 or 3.4+  
 *
 * OpenAPI spec version: 1.0.0
 * Contact: swenggroup@ubtrobot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGMediaMusicList.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGMediaMusicList::SWGMediaMusicList(QString json) {
    init();
    this->fromJson(json);
}

SWGMediaMusicList::SWGMediaMusicList() {
    init();
}

SWGMediaMusicList::~SWGMediaMusicList() {
    this->cleanup();
}

void
SWGMediaMusicList::init() {
    music = new QList<SWGName*>();
    m_music_isSet = false;
}

void
SWGMediaMusicList::cleanup() {
    if(music != nullptr) { 
        auto arr = music;
        for(auto o: *arr) { 
            delete o;
        }
        delete music;
    }
}

SWGMediaMusicList*
SWGMediaMusicList::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGMediaMusicList::fromJsonObject(QJsonObject pJson) {
    
    ::Swagger::setValue(&music, pJson["music"], "QList", "SWGName");
}

QString
SWGMediaMusicList::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
SWGMediaMusicList::asJsonObject() {
    QJsonObject obj;
    if(music->size() > 0){
        toJsonArray((QList<void*>*)music, obj, "music", "SWGName");
    }

    return obj;
}

QList<SWGName*>*
SWGMediaMusicList::getMusic() {
    return music;
}
void
SWGMediaMusicList::setMusic(QList<SWGName*>* music) {
    this->music = music;
    this->m_music_isSet = true;
}


bool
SWGMediaMusicList::isSet(){
    bool isObjectUpdated = false;
    do{
        if(music->size() > 0){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

