/**
 * Yanshee RESTful API
 *  ## 概述 Yanshee RESTful APIs是由使用[swagger-codegen](https://github.com/swagger-api/swagger-codegen)基于 [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki)的工程。 所有的API由Flask的[Connexion](https://github.com/zalando/connexion)来解释。 Yanshee-ROS中的apollo提供所有的RESTful APIs服务。 同时Yanshee RESTful APIs提供英文和中文两个版本： - [英文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [中文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## 依赖 Python 2.7 or 3.4+  
 *
 * OpenAPI spec version: 1.0.0
 * Contact: swenggroup@ubtrobot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGServosModeRequest.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGServosModeRequest::SWGServosModeRequest(QString json) {
    init();
    this->fromJson(json);
}

SWGServosModeRequest::SWGServosModeRequest() {
    init();
}

SWGServosModeRequest::~SWGServosModeRequest() {
    this->cleanup();
}

void
SWGServosModeRequest::init() {
    mode = new QString("");
    m_mode_isSet = false;
    servos = new QList<SWGServosList*>();
    m_servos_isSet = false;
}

void
SWGServosModeRequest::cleanup() {
    if(mode != nullptr) { 
        delete mode;
    }
    if(servos != nullptr) { 
        auto arr = servos;
        for(auto o: *arr) { 
            delete o;
        }
        delete servos;
    }
}

SWGServosModeRequest*
SWGServosModeRequest::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGServosModeRequest::fromJsonObject(QJsonObject pJson) {
    ::Swagger::setValue(&mode, pJson["mode"], "QString", "QString");
    
    
    ::Swagger::setValue(&servos, pJson["servos"], "QList", "SWGServosList");
}

QString
SWGServosModeRequest::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
SWGServosModeRequest::asJsonObject() {
    QJsonObject obj;
    if(mode != nullptr && *mode != QString("")){
        toJsonValue(QString("mode"), mode, obj, QString("QString"));
    }
    if(servos->size() > 0){
        toJsonArray((QList<void*>*)servos, obj, "servos", "SWGServosList");
    }

    return obj;
}

QString*
SWGServosModeRequest::getMode() {
    return mode;
}
void
SWGServosModeRequest::setMode(QString* mode) {
    this->mode = mode;
    this->m_mode_isSet = true;
}

QList<SWGServosList*>*
SWGServosModeRequest::getServos() {
    return servos;
}
void
SWGServosModeRequest::setServos(QList<SWGServosList*>* servos) {
    this->servos = servos;
    this->m_servos_isSet = true;
}


bool
SWGServosModeRequest::isSet(){
    bool isObjectUpdated = false;
    do{
        if(mode != nullptr && *mode != QString("")){ isObjectUpdated = true; break;}
        if(servos->size() > 0){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

