/**
 * Yanshee RESTful API
 *  ## 概述 Yanshee RESTful APIs是由使用[swagger-codegen](https://github.com/swagger-api/swagger-codegen)基于 [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki)的工程。 所有的API由Flask的[Connexion](https://github.com/zalando/connexion)来解释。 Yanshee-ROS中的apollo提供所有的RESTful APIs服务。 同时Yanshee RESTful APIs提供英文和中文两个版本： - [英文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [中文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## 依赖 Python 2.7 or 3.4+  
 *
 * OpenAPI spec version: 1.0.0
 * Contact: swenggroup@ubtrobot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGServosHandsRequest.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGServosHandsRequest::SWGServosHandsRequest(QString json) {
    init();
    this->fromJson(json);
}

SWGServosHandsRequest::SWGServosHandsRequest() {
    init();
}

SWGServosHandsRequest::~SWGServosHandsRequest() {
    this->cleanup();
}

void
SWGServosHandsRequest::init() {
    hands = new SWGServosHands();
    m_hands_isSet = false;
}

void
SWGServosHandsRequest::cleanup() {
    if(hands != nullptr) { 
        delete hands;
    }
}

SWGServosHandsRequest*
SWGServosHandsRequest::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGServosHandsRequest::fromJsonObject(QJsonObject pJson) {
    ::Swagger::setValue(&hands, pJson["hands"], "SWGServosHands", "SWGServosHands");
    
}

QString
SWGServosHandsRequest::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
SWGServosHandsRequest::asJsonObject() {
    QJsonObject obj;
    if((hands != nullptr) && (hands->isSet())){
        toJsonValue(QString("hands"), hands, obj, QString("SWGServosHands"));
    }

    return obj;
}

SWGServosHands*
SWGServosHandsRequest::getHands() {
    return hands;
}
void
SWGServosHandsRequest::setHands(SWGServosHands* hands) {
    this->hands = hands;
    this->m_hands_isSet = true;
}


bool
SWGServosHandsRequest::isSet(){
    bool isObjectUpdated = false;
    do{
        if(hands != nullptr && hands->isSet()){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

