/**
 * Yanshee RESTful API
 *  ## 概述 Yanshee RESTful APIs是由使用[swagger-codegen](https://github.com/swagger-api/swagger-codegen)基于 [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki)的工程。 所有的API由Flask的[Connexion](https://github.com/zalando/connexion)来解释。 Yanshee-ROS中的apollo提供所有的RESTful APIs服务。 同时Yanshee RESTful APIs提供英文和中文两个版本： - [英文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [中文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## 依赖 Python 2.7 or 3.4+  
 *
 * OpenAPI spec version: 1.0.0
 * Contact: swenggroup@ubtrobot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGSubscriptionsSensors.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGSubscriptionsSensors::SWGSubscriptionsSensors(QString json) {
    init();
    this->fromJson(json);
}

SWGSubscriptionsSensors::SWGSubscriptionsSensors() {
    init();
}

SWGSubscriptionsSensors::~SWGSubscriptionsSensors() {
    this->cleanup();
}

void
SWGSubscriptionsSensors::init() {
    type = new QString("");
    m_type_isSet = false;
    id = 0;
    m_id_isSet = false;
    slot = 0;
    m_slot_isSet = false;
    url = new QString("");
    m_url_isSet = false;
    timeout = 0;
    m_timeout_isSet = false;
    timeval = 0;
    m_timeval_isSet = false;
}

void
SWGSubscriptionsSensors::cleanup() {
    if(type != nullptr) { 
        delete type;
    }


    if(url != nullptr) { 
        delete url;
    }


}

SWGSubscriptionsSensors*
SWGSubscriptionsSensors::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGSubscriptionsSensors::fromJsonObject(QJsonObject pJson) {
    ::Swagger::setValue(&type, pJson["type"], "QString", "QString");
    
    ::Swagger::setValue(&id, pJson["id"], "qint32", "");
    
    ::Swagger::setValue(&slot, pJson["slot"], "qint32", "");
    
    ::Swagger::setValue(&url, pJson["url"], "QString", "QString");
    
    ::Swagger::setValue(&timeout, pJson["timeout"], "qint32", "");
    
    ::Swagger::setValue(&timeval, pJson["timeval"], "qint32", "");
    
}

QString
SWGSubscriptionsSensors::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
SWGSubscriptionsSensors::asJsonObject() {
    QJsonObject obj;
    if(type != nullptr && *type != QString("")){
        toJsonValue(QString("type"), type, obj, QString("QString"));
    }
    if(m_id_isSet){
        obj.insert("id", QJsonValue(id));
    }
    if(m_slot_isSet){
        obj.insert("slot", QJsonValue(slot));
    }
    if(url != nullptr && *url != QString("")){
        toJsonValue(QString("url"), url, obj, QString("QString"));
    }
    if(m_timeout_isSet){
        obj.insert("timeout", QJsonValue(timeout));
    }
    if(m_timeval_isSet){
        obj.insert("timeval", QJsonValue(timeval));
    }

    return obj;
}

QString*
SWGSubscriptionsSensors::getType() {
    return type;
}
void
SWGSubscriptionsSensors::setType(QString* type) {
    this->type = type;
    this->m_type_isSet = true;
}

qint32
SWGSubscriptionsSensors::getId() {
    return id;
}
void
SWGSubscriptionsSensors::setId(qint32 id) {
    this->id = id;
    this->m_id_isSet = true;
}

qint32
SWGSubscriptionsSensors::getSlot() {
    return slot;
}
void
SWGSubscriptionsSensors::setSlot(qint32 slot) {
    this->slot = slot;
    this->m_slot_isSet = true;
}

QString*
SWGSubscriptionsSensors::getUrl() {
    return url;
}
void
SWGSubscriptionsSensors::setUrl(QString* url) {
    this->url = url;
    this->m_url_isSet = true;
}

qint32
SWGSubscriptionsSensors::getTimeout() {
    return timeout;
}
void
SWGSubscriptionsSensors::setTimeout(qint32 timeout) {
    this->timeout = timeout;
    this->m_timeout_isSet = true;
}

qint32
SWGSubscriptionsSensors::getTimeval() {
    return timeval;
}
void
SWGSubscriptionsSensors::setTimeval(qint32 timeval) {
    this->timeval = timeval;
    this->m_timeval_isSet = true;
}


bool
SWGSubscriptionsSensors::isSet(){
    bool isObjectUpdated = false;
    do{
        if(type != nullptr && *type != QString("")){ isObjectUpdated = true; break;}
        if(m_id_isSet){ isObjectUpdated = true; break;}
        if(m_slot_isSet){ isObjectUpdated = true; break;}
        if(url != nullptr && *url != QString("")){ isObjectUpdated = true; break;}
        if(m_timeout_isSet){ isObjectUpdated = true; break;}
        if(m_timeval_isSet){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

