/**
 * Yanshee RESTful API
 *  ## 概述 Yanshee RESTful APIs是由使用[swagger-codegen](https://github.com/swagger-api/swagger-codegen)基于 [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki)的工程。 所有的API由Flask的[Connexion](https://github.com/zalando/connexion)来解释。 Yanshee-ROS中的apollo提供所有的RESTful APIs服务。 同时Yanshee RESTful APIs提供英文和中文两个版本： - [英文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [中文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## 依赖 Python 2.7 or 3.4+  
 *
 * OpenAPI spec version: 1.0.0
 * Contact: swenggroup@ubtrobot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGSensorsInfo.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGSensorsInfo::SWGSensorsInfo(QString json) {
    init();
    this->fromJson(json);
}

SWGSensorsInfo::SWGSensorsInfo() {
    init();
}

SWGSensorsInfo::~SWGSensorsInfo() {
    this->cleanup();
}

void
SWGSensorsInfo::init() {
    id = 0;
    m_id_isSet = false;
    slot = 0;
    m_slot_isSet = false;
    type = new QString("");
    m_type_isSet = false;
    version = 0;
    m_version_isSet = false;
}

void
SWGSensorsInfo::cleanup() {


    if(type != nullptr) { 
        delete type;
    }

}

SWGSensorsInfo*
SWGSensorsInfo::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGSensorsInfo::fromJsonObject(QJsonObject pJson) {
    ::Swagger::setValue(&id, pJson["id"], "qint32", "");
    
    ::Swagger::setValue(&slot, pJson["slot"], "qint32", "");
    
    ::Swagger::setValue(&type, pJson["type"], "QString", "QString");
    
    ::Swagger::setValue(&version, pJson["version"], "qint32", "");
    
}

QString
SWGSensorsInfo::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
SWGSensorsInfo::asJsonObject() {
    QJsonObject obj;
    if(m_id_isSet){
        obj.insert("id", QJsonValue(id));
    }
    if(m_slot_isSet){
        obj.insert("slot", QJsonValue(slot));
    }
    if(type != nullptr && *type != QString("")){
        toJsonValue(QString("type"), type, obj, QString("QString"));
    }
    if(m_version_isSet){
        obj.insert("version", QJsonValue(version));
    }

    return obj;
}

qint32
SWGSensorsInfo::getId() {
    return id;
}
void
SWGSensorsInfo::setId(qint32 id) {
    this->id = id;
    this->m_id_isSet = true;
}

qint32
SWGSensorsInfo::getSlot() {
    return slot;
}
void
SWGSensorsInfo::setSlot(qint32 slot) {
    this->slot = slot;
    this->m_slot_isSet = true;
}

QString*
SWGSensorsInfo::getType() {
    return type;
}
void
SWGSensorsInfo::setType(QString* type) {
    this->type = type;
    this->m_type_isSet = true;
}

qint32
SWGSensorsInfo::getVersion() {
    return version;
}
void
SWGSensorsInfo::setVersion(qint32 version) {
    this->version = version;
    this->m_version_isSet = true;
}


bool
SWGSensorsInfo::isSet(){
    bool isObjectUpdated = false;
    do{
        if(m_id_isSet){ isObjectUpdated = true; break;}
        if(m_slot_isSet){ isObjectUpdated = true; break;}
        if(type != nullptr && *type != QString("")){ isObjectUpdated = true; break;}
        if(m_version_isSet){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

