/**
 * Yanshee RESTful API
 *  ## 概述 Yanshee RESTful APIs是由使用[swagger-codegen](https://github.com/swagger-api/swagger-codegen)基于 [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki)的工程。 所有的API由Flask的[Connexion](https://github.com/zalando/connexion)来解释。 Yanshee-ROS中的apollo提供所有的RESTful APIs服务。 同时Yanshee RESTful APIs提供英文和中文两个版本： - [英文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [中文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## 依赖 Python 2.7 or 3.4+  
 *
 * OpenAPI spec version: 1.0.0
 * Contact: swenggroup@ubtrobot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGSubscriptionsSensorsDelete.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGSubscriptionsSensorsDelete::SWGSubscriptionsSensorsDelete(QString json) {
    init();
    this->fromJson(json);
}

SWGSubscriptionsSensorsDelete::SWGSubscriptionsSensorsDelete() {
    init();
}

SWGSubscriptionsSensorsDelete::~SWGSubscriptionsSensorsDelete() {
    this->cleanup();
}

void
SWGSubscriptionsSensorsDelete::init() {
    type = new QString("");
    m_type_isSet = false;
    id = 0;
    m_id_isSet = false;
    slot = 0;
    m_slot_isSet = false;
    url = new QString("");
    m_url_isSet = false;
    timeval = 0;
    m_timeval_isSet = false;
}

void
SWGSubscriptionsSensorsDelete::cleanup() {
    if(type != nullptr) { 
        delete type;
    }


    if(url != nullptr) { 
        delete url;
    }

}

SWGSubscriptionsSensorsDelete*
SWGSubscriptionsSensorsDelete::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGSubscriptionsSensorsDelete::fromJsonObject(QJsonObject pJson) {
    ::Swagger::setValue(&type, pJson["type"], "QString", "QString");
    
    ::Swagger::setValue(&id, pJson["id"], "qint32", "");
    
    ::Swagger::setValue(&slot, pJson["slot"], "qint32", "");
    
    ::Swagger::setValue(&url, pJson["url"], "QString", "QString");
    
    ::Swagger::setValue(&timeval, pJson["timeval"], "qint32", "");
    
}

QString
SWGSubscriptionsSensorsDelete::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
SWGSubscriptionsSensorsDelete::asJsonObject() {
    QJsonObject obj;
    if(type != nullptr && *type != QString("")){
        toJsonValue(QString("type"), type, obj, QString("QString"));
    }
    if(m_id_isSet){
        obj.insert("id", QJsonValue(id));
    }
    if(m_slot_isSet){
        obj.insert("slot", QJsonValue(slot));
    }
    if(url != nullptr && *url != QString("")){
        toJsonValue(QString("url"), url, obj, QString("QString"));
    }
    if(m_timeval_isSet){
        obj.insert("timeval", QJsonValue(timeval));
    }

    return obj;
}

QString*
SWGSubscriptionsSensorsDelete::getType() {
    return type;
}
void
SWGSubscriptionsSensorsDelete::setType(QString* type) {
    this->type = type;
    this->m_type_isSet = true;
}

qint32
SWGSubscriptionsSensorsDelete::getId() {
    return id;
}
void
SWGSubscriptionsSensorsDelete::setId(qint32 id) {
    this->id = id;
    this->m_id_isSet = true;
}

qint32
SWGSubscriptionsSensorsDelete::getSlot() {
    return slot;
}
void
SWGSubscriptionsSensorsDelete::setSlot(qint32 slot) {
    this->slot = slot;
    this->m_slot_isSet = true;
}

QString*
SWGSubscriptionsSensorsDelete::getUrl() {
    return url;
}
void
SWGSubscriptionsSensorsDelete::setUrl(QString* url) {
    this->url = url;
    this->m_url_isSet = true;
}

qint32
SWGSubscriptionsSensorsDelete::getTimeval() {
    return timeval;
}
void
SWGSubscriptionsSensorsDelete::setTimeval(qint32 timeval) {
    this->timeval = timeval;
    this->m_timeval_isSet = true;
}


bool
SWGSubscriptionsSensorsDelete::isSet(){
    bool isObjectUpdated = false;
    do{
        if(type != nullptr && *type != QString("")){ isObjectUpdated = true; break;}
        if(m_id_isSet){ isObjectUpdated = true; break;}
        if(m_slot_isSet){ isObjectUpdated = true; break;}
        if(url != nullptr && *url != QString("")){ isObjectUpdated = true; break;}
        if(m_timeval_isSet){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

