/**
 * Yanshee RESTful API
 *  ## 概述 Yanshee RESTful APIs是由使用[swagger-codegen](https://github.com/swagger-api/swagger-codegen)基于 [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki)的工程。 所有的API由Flask的[Connexion](https://github.com/zalando/connexion)来解释。 Yanshee-ROS中的apollo提供所有的RESTful APIs服务。 同时Yanshee RESTful APIs提供英文和中文两个版本： - [英文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [中文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## 依赖 Python 2.7 or 3.4+  
 *
 * OpenAPI spec version: 1.0.0
 * Contact: swenggroup@ubtrobot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGServosHands.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGServosHands::SWGServosHands(QString json) {
    init();
    this->fromJson(json);
}

SWGServosHands::SWGServosHands() {
    init();
}

SWGServosHands::~SWGServosHands() {
    this->cleanup();
}

void
SWGServosHands::init() {
    left = 0;
    m_left_isSet = false;
    right = 0;
    m_right_isSet = false;
}

void
SWGServosHands::cleanup() {


}

SWGServosHands*
SWGServosHands::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGServosHands::fromJsonObject(QJsonObject pJson) {
    ::Swagger::setValue(&left, pJson["left"], "qint32", "");
    
    ::Swagger::setValue(&right, pJson["right"], "qint32", "");
    
}

QString
SWGServosHands::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
SWGServosHands::asJsonObject() {
    QJsonObject obj;
    if(m_left_isSet){
        obj.insert("left", QJsonValue(left));
    }
    if(m_right_isSet){
        obj.insert("right", QJsonValue(right));
    }

    return obj;
}

qint32
SWGServosHands::getLeft() {
    return left;
}
void
SWGServosHands::setLeft(qint32 left) {
    this->left = left;
    this->m_left_isSet = true;
}

qint32
SWGServosHands::getRight() {
    return right;
}
void
SWGServosHands::setRight(qint32 right) {
    this->right = right;
    this->m_right_isSet = true;
}


bool
SWGServosHands::isSet(){
    bool isObjectUpdated = false;
    do{
        if(m_left_isSet){ isObjectUpdated = true; break;}
        if(m_right_isSet){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

