/**
 * Yanshee RESTful API
 *  ## 概述 Yanshee RESTful APIs是由使用[swagger-codegen](https://github.com/swagger-api/swagger-codegen)基于 [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki)的工程。 所有的API由Flask的[Connexion](https://github.com/zalando/connexion)来解释。 Yanshee-ROS中的apollo提供所有的RESTful APIs服务。 同时Yanshee RESTful APIs提供英文和中文两个版本： - [英文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [中文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## 依赖 Python 2.7 or 3.4+  
 *
 * OpenAPI spec version: 1.0.0
 * Contact: swenggroup@ubtrobot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGVisionsStream.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGVisionsStream::SWGVisionsStream(QString json) {
    init();
    this->fromJson(json);
}

SWGVisionsStream::SWGVisionsStream() {
    init();
}

SWGVisionsStream::~SWGVisionsStream() {
    this->cleanup();
}

void
SWGVisionsStream::init() {
    resolution = new QString("");
    m_resolution_isSet = false;
}

void
SWGVisionsStream::cleanup() {
    if(resolution != nullptr) { 
        delete resolution;
    }
}

SWGVisionsStream*
SWGVisionsStream::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGVisionsStream::fromJsonObject(QJsonObject pJson) {
    ::Swagger::setValue(&resolution, pJson["resolution"], "QString", "QString");
    
}

QString
SWGVisionsStream::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
SWGVisionsStream::asJsonObject() {
    QJsonObject obj;
    if(resolution != nullptr && *resolution != QString("")){
        toJsonValue(QString("resolution"), resolution, obj, QString("QString"));
    }

    return obj;
}

QString*
SWGVisionsStream::getResolution() {
    return resolution;
}
void
SWGVisionsStream::setResolution(QString* resolution) {
    this->resolution = resolution;
    this->m_resolution_isSet = true;
}


bool
SWGVisionsStream::isSet(){
    bool isObjectUpdated = false;
    do{
        if(resolution != nullptr && *resolution != QString("")){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

