/**
 * Yanshee RESTful API
 *  ## 概述 Yanshee RESTful APIs是由使用[swagger-codegen](https://github.com/swagger-api/swagger-codegen)基于 [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki)的工程。 所有的API由Flask的[Connexion](https://github.com/zalando/connexion)来解释。 Yanshee-ROS中的apollo提供所有的RESTful APIs服务。 同时Yanshee RESTful APIs提供英文和中文两个版本： - [英文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [中文版本](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## 依赖 Python 2.7 or 3.4+  
 *
 * OpenAPI spec version: 1.0.0
 * Contact: swenggroup@ubtrobot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGVoiceDeleteOfflineSyntax.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGVoiceDeleteOfflineSyntax::SWGVoiceDeleteOfflineSyntax(QString json) {
    init();
    this->fromJson(json);
}

SWGVoiceDeleteOfflineSyntax::SWGVoiceDeleteOfflineSyntax() {
    init();
}

SWGVoiceDeleteOfflineSyntax::~SWGVoiceDeleteOfflineSyntax() {
    this->cleanup();
}

void
SWGVoiceDeleteOfflineSyntax::init() {
    grammar = new QString("");
    m_grammar_isSet = false;
}

void
SWGVoiceDeleteOfflineSyntax::cleanup() {
    if(grammar != nullptr) { 
        delete grammar;
    }
}

SWGVoiceDeleteOfflineSyntax*
SWGVoiceDeleteOfflineSyntax::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGVoiceDeleteOfflineSyntax::fromJsonObject(QJsonObject pJson) {
    ::Swagger::setValue(&grammar, pJson["grammar"], "QString", "QString");
    
}

QString
SWGVoiceDeleteOfflineSyntax::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
SWGVoiceDeleteOfflineSyntax::asJsonObject() {
    QJsonObject obj;
    if(grammar != nullptr && *grammar != QString("")){
        toJsonValue(QString("grammar"), grammar, obj, QString("QString"));
    }

    return obj;
}

QString*
SWGVoiceDeleteOfflineSyntax::getGrammar() {
    return grammar;
}
void
SWGVoiceDeleteOfflineSyntax::setGrammar(QString* grammar) {
    this->grammar = grammar;
    this->m_grammar_isSet = true;
}


bool
SWGVoiceDeleteOfflineSyntax::isSet(){
    bool isObjectUpdated = false;
    do{
        if(grammar != nullptr && *grammar != QString("")){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

