#ifndef COMMUNICATION_GLOBAL_H
#define COMMUNICATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMUNICATION_LIBRARY)
#  define COMMUNICATION_EXPORT Q_DECL_EXPORT
#else
#  define COMMUNICATION_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMUNICATION_GLOBAL_H
